simplesocial/accounts/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views as acc_views

app_name = 'accounts'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', acc_views.SignUpView.as_view(), name='signup'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views as post_views

app_name = 'posts'

urlpatterns = [
    path('', post_views.PostList.as_view(), name='all'),
    path('new/', post_views.CreatePost.as_view(), name='create'),
    path('by/<slug:username>', post_views.UserPosts.as_view(), name='for_user'),
    path('post/<slug:username>/<slug:pk>/', post_views.PostDetail.as_view(), name='post_single'),
    path('delete/<slug:pk>/', post_views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as home_views

urlpatterns = [
    path('', home_views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('test/', home_views.TestPageView.as_view(), name = 'test'),
    path('thanks/', home_views.ThanksPageView.as_view(), name = 'thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

simplesocial/simplesocial/views.py
from django.views.generic import TemplateView

# Define Views Here
class HomePage(TemplateView):
    template_name = 'index.html'

class TestPageView(TemplateView):
    template_name = 'test.html'

class ThanksPageView(TemplateView):
    template_name = 'thanks.html'

simplesocial/simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
        crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
    {% block header_block %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light mynav" role="navigation" id="navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerMain"
            aria-controls="navbarTogglerMain" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerMain">
            <a class="navbar-brand mynav" href="{% url 'home' %}">SciFi Social</a>
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:create' %}">Post</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'groups:create' %}">Create Group</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mycontent">
        {% block content_block %}
        {% endblock %}
    </div>
</body </html>

simplesocial/simplesocial/templates/index.html
{% extends "base.html" %}

{% block header_block %}
<title>SciFi Social</title>
{% endblock %}

{% block content_block %}
<h1>Welcome to SciFi Social!</h1>
{% endblock %}

simplesocial/simplesocial/templates/test.html
{% extends "base.html" %}

{% block header_block %}
<title>SciFi Social</title>
{% endblock %}

{% block content_block %}
<h1>Test!</h1>
{% endblock %}

simplesocial/simplesocial/templates/thanks.html
{% extends "base.html" %}

{% block header_block %}
<title>SciFi Social</title>
{% endblock %}

{% block content_block %}
<h1>Thanks for Visiting! Come back soon!</h1>
{% endblock %}