django_template/basic_app/urls.py
from django.urls import path, include
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('create/', views.SchoolCreate.as_view(), name='create_school'),
    path('detail/<slug:pk>', views.SchoolDetailView.as_view(), name='school_detail'),
    path('update/<slug:pk>', views.SchoolUpdate.as_view(), name='update_school'),
    path('delete/<slug:pk>', views.SchoolDelete.as_view(), name='delete_school')
]

django_template/django_template/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('home/',views.IndexView.as_view(), name='home'),
    path('basic_app/', include('basic_app.urls')),
    #path('', views.CBView.as_view(), name='index'),
    # path('', views.index, name='index'),
]

django_template/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=128, unique=True)
    size = models.PositiveIntegerField()
    site = models.URLField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:school_detail", kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=128, unique=True)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete='CASCADE')

    def __str__(self):
        rstr = ' '.join([self.name,'(', str(self.age), ')'])
        return rstr

django_template/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.http import HttpResponse
from . import models

# Create your views here.

#Function-based view
# def index(request):
#     return render(request, 'index.html')

#Class-based view
# class CBView(View):
#     def get(self, request):
#         return HttpResponse("Class Based Views are COOL!")

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injected_content'] = 'Basic Injection!'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    #Inherited listview school_list natively.  forced to 'schools'

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreate(CreateView):
    model = models.School
    fields = ('name', 'size', 'site')
    template_name = 'basic_app/school_form.html'
    
class SchoolUpdate(UpdateView):
    model = models.School
    fields = ('size', 'site')

class SchoolDelete(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

django_template/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Basic_App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">SchoolsHome</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-link" href="/">Project Home</a></li>
                <li><a class="nav-link" href="{% url 'basic_app:create_school' %}">Add School</a></li>
            </ul>
        </nav>

            {% block body_block %}

            {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

django_template/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{url 'basic_app:detail' pk=school.pk}">Cancel</a>
</form>
{% endblock %}

django_template/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h1>School Details Page</h1>
        <h2>Information Follows:</h2>
        <p>Name: {{school_detail.name}}</p>
        <p>Size: {{school_detail.size}}</p>
        <p>Site: {{school_detail.site}}</p>
        <h3>Students</h3>
 
            {% for student in school_detail.students.all %}
                <p>{{student.name}} ({{student.age}})</p>
            {% endfor %}
    </div>
    <div>
        <p><a class="btn btn-secondary" href="{% url 'basic_app:update_school' pk=school_detail.pk %}">Update Information</a></p>
        <p><a class="btn btn-warning" href="{%url 'basic_app:delete_school' pk=school_detail.pk %}">Delete School</a></p>
    </div>
{% endblock %}

django_template/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
    </h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group row">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}" class="col-2 col-form-label">Name: </label>
            <div class="col-4">{{ form.name }}</div>
        </div>
        <div class="form-group row">
            {{ form.size.errors }}
            <label for="{{ form.size.id_for_label }}" class="col-2 col-form-label">Size: </label>
            <div class="col-4">{{ form.size }}</div>
        </div>
        <div class="form-group row">
            {{ form.site.errors }}
            <label for="{{ form.site.id_for_label }}" class="col-2 col-form-label">School Website: </label>
            <div class="col-4">{{ form.site }}</div>
        </div>    
        <input type="submit" class="btn-lg btn-primary" value="Save">
    </form>
</div>

{% endblock %}

django_template/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h1>List of All Recorded Schools</h1>
        <ol>
            {% for school in schools %}
                <h2><li><a href="detail/{{school.id}}">{{school.name}}</a></li></h2>
            {% endfor %}
        </ol>
    </div>


{% endblock %}

django_template/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

</head>
<body>
    <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="/home">Navbar-Brand</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                  
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="/admin">Admin</a>
                        </li>
                        <li>
                          <a class="nav-link" href="/basic_app">Basic_App</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                          </div>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                      </ul>
                      <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                      </form>
                    </div>
                  </nav>

            {% block body_block %}

            {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

django_template/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
         <h1>Hello World! Index Page Home</h1>
    </div>

    <h2>Injected Content: {{ injected_content }}</h2>
    
{% endblock %}