simplesocial/groups/urls.py
from django.urls import path
from groups import views as group_views

app_name = 'groups'

urlpatterns = [
    path('', group_views.ListGroups.as_view(), name='all'),
    path('new/', group_views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug:slug>/',group_views.SingleGroup.as_view(), name='single'),
    path('join/<slug:slug>/', group_views.JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>/', group_views.LeaveGroup.as_view(), name='leave'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views as post_views

app_name = 'posts'

urlpatterns = [
    path('', post_views.PostList.as_view(), name='all'),
    path('new/', post_views.CreatePost.as_view(), name='create'),
    path('by/<slug:username>', post_views.UserPosts.as_view(), name='for_user'),
    path('post/<slug:username>/<slug:pk>/', post_views.PostDetail.as_view(), name='post_single'),
    path('delete/<slug:pk>/', post_views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as home_views

urlpatterns = [
    path('', home_views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('test/', home_views.TestPageView.as_view(), name = 'test'),
    path('thanks/', home_views.ThanksPageView.as_view(), name = 'thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

simplesocial/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete="CASCADE")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete="CASCADE")

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post_single', kwargs={'username':self.user.username,
                                                'pk':self.pk})
                                        
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

simplesocial/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import models
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model

# Create your views here.

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'post/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):

    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

simplesocial/posts/templates/posts/_post.html
<div class="post media">
        <h3>{{ post.message_html|safe }}</h3>
        <div class="media-body">
            <strong>{{ post.user.username }}</strong>
            <h5 class="media-heading">
                <span class="username">
                    <a href="{% url 'posts:for_user' username=post.user.username}"></a>
                </span>
    
                <time class="time">
                    <a href="{% url 'posts:post_single' username=post.user.username pk=post.pk %}"></a>
                </time>
            </h5>
    
            <div class="media-footer">
                {% if user.is_authenticated and post.user == user %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-warning">
                    <span class="glyphicon glyphicon-remove text-danger" aria-hidden='true'></span>
                    <span class="text-danger icon-label">Delete</span>
                </a>
                {% endif %}
            </div>
    
        </div>
    </div>

simplesocial/posts/templates/posts/_posts.html
<div class="post media">
        <h3>{{ post.message_html|safe }}</h3>
        <div class="media-body">
            <strong>{{ post.user.username }}</strong>
            <h5 class="media-heading">
                <span class="username">
                    <a href="{% url 'posts:for_user' username=post.user.username}"></a>
                </span>
    
                <time class="time">
                    <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"></a>
                </time>
            </h5>
    
            <div class="media-footer">
                {% if user.is_authenticated and post.user == user %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-warning">
                    <span class="glyphicon glyphicon-remove text-danger" aria-hidden='true'></span>
                    <span class="text-danger icon-label">Delete</span>
                </a>
                {% endif %}
            </div>
    
        </div>
    </div>

simplesocial/posts/templates/posts/post_base.html
{% extends "base.html" %}
    {% block content_block %}
        <div class="posts-page">
            <div class="container">
                <div class="row">
                    {% block prepost %}{% endblock %}
                    {% block post_content %}{% endblock %}
                    {% block post_post %}{% endblock %}
                </div>
            </div>
        </div>
    {% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>
<div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
    {% csrf_token %}
    <input type="submit" name="" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-secondary btn-lg btn-default">Cancel</a>
</form>

{% endblock %}

simplesocial/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}

{% block post_content %}
<div class="container">
    <h4>Create a new Post</h4>
</div>
<div class="container">
    <form id="postForm" action="{% url 'posts:create' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Post" class="btn btn-primary btn-lg">
    </form>
</div>

{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends post/post_base.html %}
{% block prepost %}
<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">Your Groups:</h5>
            <ul class="list-unstyled">
                {% for member_group in get_user_groups %}
                <li><a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.name }}</a></li>
                {% enfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="content">All Groups:</h5>
            <ul class="list-unstyled">
                {% for other_group in get_other_groups %}
                <li><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
        {% include "posts/_post.html" %}
    {% endfor %}
</div>
{% endblock %}

simplesocial/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
<div class="col-md-4">
    <h1>@{{ post_user.username }}</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
        {% include "posts/_post.html" %}
    {% endfor %}

</div>
{% endblock %}