simplesocial/groups/urls.py
from django.urls import path
from groups import views as group_views

app_name = 'groups'

urlpatterns = [
    path('', group_views.ListGroups.as_view(), name='all'),
    path('new/', group_views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug:slug>/',group_views.SingleGroup.as_view(), name='single'),
    path('join/<slug:slug>/', group_views.JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>/', group_views.LeaveGroup.as_view(), name='leave'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views as post_views

app_name = 'posts'

urlpatterns = [
    path('', post_views.PostList.as_view(), name='all'),
    path('new/', post_views.CreatePost.as_view(), name='create'),
    path('by/<slug:username>', post_views.UserPosts.as_view(), name='for_user'),
    path('post/<slug:username>/<slug:pk>/', post_views.PostDetail.as_view(), name='post_single'),
    path('delete/<slug:pk>/', post_views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as home_views

urlpatterns = [
    path('', home_views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('test/', home_views.TestPageView.as_view(), name = 'test'),
    path('thanks/', home_views.ThanksPageView.as_view(), name = 'thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

simplesocial/groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django import template

import misaka

## GROUPS MODELS.PY FILE
# Create your models here.
User = get_user_model()
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMembers')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMembers(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete="CASCADE")
    user = models.ForeignKey(User, related_name='user_groups', on_delete="CASCADE")

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')
    

simplesocial/groups/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages

from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404

from groups.models import Group, GroupMembers

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMembers.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request,'Warning.  Already a member.')
        else:
            messages.success(self.request,'You are now a member!')

        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMembers.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug'),
            ).get()
        except GroupMembers.DoesNotExist:
            messages.warning(self.request, 'Sorry, you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group')
        
        return super().get(request, *args, **kwargs)

simplesocial/groups/templates/groups/group.detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<h1>{{ group.name }}</h1>
<h2>Member Count: {{ group.members.count }}</h2>

<div class="content">
    {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" 
            class="btn btn-lg btn-outline-warning"><span class="glyphicon glyphicon-remove-circle"></span>Leave Group</a>
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" 
        class="btn btn-lg btn-outline-primary"><span class="glyphicon glyphicon-ok-circle"></span>Join Group</a>
    {% endif %}
</div>
{% block endblock%}

{% block group_content %}
<div class="col-md-8">
    {% if group.posts.count == 0 %}
    <h2>No Posts Yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %} 
            <!-- _post to be injected -->
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content_block %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>


{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    <div class="container">
        <h1>{{ group.name }}</h1>
        <h2>Member Count: {{ group.members.count }}</h2>
    



<div class="content">
    {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" 
            class="btn btn-lg btn-outline-warning"><span class="glyphicon glyphicon-remove-circle"></span>Leave Group</a>
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" 
        class="btn btn-lg btn-outline-primary"><span class="glyphicon glyphicon-ok-circle"></span>Join Group</a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    {% if group.posts.count == 0 %}
    <h2>No Posts Yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %} 
            <!-- _post to be injected -->
        {% endfor %}
    {% endif %}
</div>
{% endblock %}
</div>

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}

{% block group_content %}
<h4>Create a new group:</h4>
<div class="container">
    <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-lg" value="Create">
    </form>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back
            <a href="{% url 'posts:for_user' username=user.username %}">
                @{{ user.username }}
            </a>
        </h2>
        
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the SciFi Social Groups Page</p>
    </div>
    {% if  user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-dark">
        <span class="glyphicon glyphicon-plus-sign">Create New Group</span>
    </a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
        <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
            <h3 class="title list-group-item-heading">{{ group.name }}
                <div class="list-group-item-text container-fluid">
                    {{ group.description_html|safe }}
                <div class="row">
                    <div class="col-md-4">
                        <span class="badge">{{ group.members.count }}</span>
                        member{{ group.members.count|pluralize }}
                    </div>
                    <div class="col-md-4">
                        <span class="badge">{{ group.post.count }}</span>
                        post{{ group.posts.count|pluralize }}
                    </div>
                </div>
                </div>
            </h3>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}